// ============================================================================
// Empire Engine — core type contract. ADD fields freely; never rename/remove.
// ============================================================================

export type IndustryType =
  | 'tech'
  | 'space'
  | 'culinary'
  | 'energy'
  | 'fashion'
  | 'biotech'
  | 'media'
  | 'agri';

export type Philosophy = 'innovator' | 'efficiency' | 'people_first' | 'aggressive';
export type Rarity = 'common' | 'rare' | 'epic' | 'legendary';
export type ResearchBranch = 'production' | 'efficiency' | 'innovation' | 'market' | 'legacy';
export type Speaker = 'mentor' | 'rival' | 'partner' | 'consortium' | 'narrator' | 'player';

export interface FacilityConfig {
  id: string;
  tier: number;
  name: string;
  desc: string;
  icon: string;
  baseCost: number;
  costMul: number;
  baseRate: number;
}

export interface IndustryConfig {
  id: IndustryType;
  name: string;
  tagline: string;
  emoji: string;
  accent: string;
  resource: string;
  resourceShort: string;
  currency: string;
  mechanicName: string;
  mechanicDesc: string;
  chain: [string, string, string, string, string];
  advisorTitles: string[];
  facilities: FacilityConfig[];
  tierUnlock: [number, number, number, number, number];
}

export interface ResearchNode {
  id: string;
  branch: ResearchBranch;
  name: string;
  desc: string;
  tier: number;
  cost: number;
  timeSec: number;
  effect: {
    kind: 'production' | 'cost' | 'insight' | 'prestige' | 'market' | 'offline' | 'advisor';
    value: number;
  };
  requires: string[];
}

export interface StoryChoiceOption {
  text: string;
  ethicsShift: number;
  reward?: GameReward;
}

export interface StoryBeat {
  id: string;
  act: number;
  chapter: number;
  title: string;
  trigger: {
    type: 'start' | 'earnings' | 'tier' | 'prestige' | 'territory' | 'research' | 'advisor';
    value?: number;
  };
  speaker: Speaker;
  lines: string[];
  choice?: { prompt: string; options: StoryChoiceOption[] };
  reward?: GameReward;
  /** Marks a cinematic beat: darker overlay, speaker glow, enhanced modal staging. */
  dramatic?: boolean;
}

// ============================================================================
// Ambient feed (Session 4.4) — lightweight dispatch channel for in-world events.
// Short narrative moments auto-generated by engine transitions (rival telegraphs,
// companion rung upgrades, workforce mood shifts, etc.) — no modal, no queue.
// ============================================================================

export interface AmbientEntry {
  id: string;
  at: number;   // ms timestamp
  icon: string;
  source: string;
  text: string;
}

export interface Advisor {
  id: string;
  name: string;
  title: string;
  rarity: Rarity;
  maxLevel: number;
  industry: IndustryType;
  passiveBonus: {
    kind: 'production' | 'cost' | 'insight' | 'influence' | 'market';
    value: number;
  };
  activeAbility?: {
    name: string;
    description: string;
    cooldownSeconds: number;
    mult: number;
    durationSec: number;
  };
  flavorText: string;
  icon: string;
}

export interface RegionConfig {
  id: string;
  name: string;
  emoji: string;
  bonusDesc: string;
  bonusKind: 'production' | 'market' | 'insight' | 'influence';
  bonusValue: number;
  unlockCost: number;
  expandSeconds: number;
  rival: string;
}

// ============================================================================
// Marketing + Character + Guidance (additive systems)
// ============================================================================

export interface AvatarConfig {
  skin: number;
  hair: number;
  hairColor: number;
  outfit: number;
  accessory: number;
  expression: number;
  accent: string;
}

export interface CofounderState {
  name: string;
  role: string;
  avatar: AvatarConfig;
}

export interface MarketingChannelState {
  level: number;
  active: boolean;
  invested: number;
  progressMs: number;
}

export interface ActiveCampaign {
  id: string;
  name: string;
  endsAt: number;
  reachMult: number;
}

export interface MarketingState {
  reach: number;
  audience: number;
  followers: number;
  brand: number;
  channels: Record<string, MarketingChannelState>;
  campaign: ActiveCampaign | null;
}

export interface GuidanceState {
  seen: string[];
  queue: string[];
  dismissed: string[];
  lastShownAt: number;
}

export interface GameReward {
  cash?: number;
  insight?: number;
  influence?: number;
  lp?: number;
  advisorId?: string;
  boost?: { mult: number; seconds: number };
}

export interface CompanySetup {
  name: string;
  industry: IndustryType;
  accent: string;
  philosophy: Philosophy;
  foundedAt: number;
}

export interface ActiveResearch {
  id: string;
  startedAt: number;
  endsAt: number;
}

export interface ActiveBoost {
  mult: number;
  endsAt: number;
  source: string;
}

export interface ExpandingRegion {
  id: string;
  endsAt: number;
}

export interface GameState {
  version: number;
  setup: CompanySetup | null;
  cash: number;
  resource: number;
  lifetimeEarnings: number;
  insight: number;
  influence: number;
  legacyPoints: number;
  prestigeCount: number;
  masteryStars: number;
  transcendShards: number;
  facilities: Record<string, number>;
  research: { completed: string[]; active: ActiveResearch | null };
  advisors: {
    owned: Record<string, number>;
    assigned: Record<string, string>;
    cooldowns: Record<string, number>;
  };
  story: { seen: string[]; queue: string[]; ethics: number; act: number };
  territory: { unlocked: string[]; expanding: ExpandingRegion | null };
  market: {
    priceMul: number;
    trend: number;
    history: number[];
    demandShiftAt: number;
    stockpiling: boolean;
  };
  events: { boost: ActiveBoost | null; lastMicroAt: number; bubbleAt: number };
  milestones: { unlocked: string[] };
  marketing: MarketingState;
  cofounder: CofounderState;
  guidance: GuidanceState;
  settings: { sound: boolean; buyQty: 1 | 10 | 100 | 'max'; liveView: boolean };
  stats: { clicks: number; playSeconds: number; prestiges: number; created: number };
  // Accumulated seconds spent at a visionary reputation (ethics > 20).
  reputationHeldSec: number;
  // Director system (Session 3.5).
  director: DirectorState;
  // Companion system (Session 3.4).
  companions: CompanionState[];
  /** Active companion boosts (counsel/rally/signature effects currently running). */
  companionBoosts: Array<{ companionId: string; mult: number; endsAt: number }>;
  // Rival system (Sessions 3.2–3.3).
  rivals: RivalState[];
  rivalPressures: RivalPressure[];
  coalitionActive: boolean;
  // Workforce system (Session 4.1).
  workforce: WorkerState[];
  // Aide system (Session 4.2).
  aides: AideState[];
  // Premise system (Session 4.3) — Old Master's inheritance with clauses.
  premise: PremiseState | null;
  // Ambient feed (Session 4.4) — auto-generated dispatch from engine transitions.
  ambientFeed: AmbientEntry[];
  // Dynasty system (Session 4.5) — prestige chain and earned traits.
  dynasty: DynastyState;
  /** Story beats generated dynamically by emergent beat templates. */
  generatedBeats: StoryBeat[];
  // Echelon system (Session 5.1) — competitive ranking ladder.
  echelon: EchelonState;
  // Intel Desk (Session 5.2) — spy network for rival intelligence.
  intel: IntelState;
  // Newspaper (Session 5.3) — press coverage and brand heat.
  newspaper: NewspaperState;
  // Notification Engine (Session 5.4) — persistent prioritised alert log.
  notifications: NotificationState;
  lastTick: number;
  lastSaved: number;
}

export interface OfflineSummary {
  seconds: number;
  cash: number;
  insight: number;
  events: string[];
}

// ============================================================================
// Premise system (Session 4.3) — Old Master's inheritance with named clauses.
// Each clause evaluates a game-state condition; once sustained long enough it
// locks in a production/cost bonus. Breaching a fulfilled clause suspends the
// bonus until the condition is re-earned.
// ============================================================================

export type ClauseStatus = 'locked' | 'progressing' | 'fulfilled' | 'breached';

export interface PremiseClause {
  id: string;
  status: ClauseStatus;
  /** Seconds the condition has been continuously met (resets on break). */
  holdSec: number;
  /** ms timestamp when first fulfilled; 0 if never. */
  fulfilledAt: number;
  /** Seconds the condition has been broken while in the grace window. */
  breachSec: number;
}

export interface PremiseState {
  /** ms timestamp when the will was first revealed to the player. */
  revealedAt: number;
  clauses: PremiseClause[];
}

// ============================================================================
// Workforce system (Session 4.1) — named employees with morale.
// Collective morale drives a production multiplier: happy team → more output.
// ============================================================================

export type WorkerMood = 'BURNT_OUT' | 'DISENGAGED' | 'NEUTRAL' | 'ENGAGED' | 'INSPIRED';

export interface WorkerState {
  id: string;
  name: string;
  role: string;
  morale: number;      // 0–100
  hiredAt: number;     // ms timestamp
  lastEventAt: number; // ms timestamp — gates player-triggered morale boosts
}

// ============================================================================
// Aide system (Session 4.2) — six domain specialists in the player's cabinet.
// Loyalty (0–100) drifts based on ethics/rivals/companions; at ≥75 a passive
// production bonus is active; player can Brief (+loyalty) or Deploy (boost).
// ============================================================================

export type AideDomain = 'legal' | 'pr' | 'finance' | 'tech' | 'logistics' | 'creative';

export interface AideState {
  id: string;
  loyalty: number;             // 0–100
  lastBriefAt: number;         // ms — gates Brief button (120 s cooldown)
  deployCooldownUntil: number; // ms — gates Deploy button (600 s cooldown)
}

// ============================================================================
// Companion system (Session 3.4) — mirror of the rival system.
// Where rivals have aggression that rises and strikes, companions have trust
// that rises and gives.
// ============================================================================

export type TrustRung =
  | 'ACQUAINTANCE' // just joined — words and small help
  | 'COLLEAGUE'    // reliable — steady passive benefit
  | 'CONFIDANT'    // trusted — active counsel and warnings
  | 'INNER_CIRCLE' // deeply loyal — signature ability, public defence
  | 'LEGACY'       // terminal positive — survives prestige resets
  | 'ESTRANGED';   // terminal negative — betrayed past recovery

/** A supportive action the companion takes based on current need. */
export interface CompanionMove {
  kind:
    | 'counsel'       // warns before a costly mistake
    | 'cover'         // absorbs one rival hit
    | 'boost'         // passive production multiplier
    | 'rally'         // temporary surge in a crisis
    | 'loyalty_save'  // refuses a rival's poach attempt
    | 'signature';    // standout active power
  message: string;
  /** Multiplier applied (for boost/rally/signature). */
  mult?: number;
  /** Duration in seconds (for temporary effects). */
  durationSec?: number;
}

export interface CompanionState {
  id: string;
  trust: number;     // 0–100
  rung: TrustRung;
  lastActionAt: number;
  cooldownUntil: number;
  pendingTrustDelta: number;
  /** Accumulated seconds at Inner Circle+ (drives signature ability growth). */
  loyaltyHeldSec: number;
}

// ============================================================================
// Rival system (Session 3.2)
// ============================================================================

export type RivalPosture =
  | 'DORMANT'
  | 'WATCHING'
  | 'PROVOKED'
  | 'HOSTILE'
  | 'WAR'
  | 'DEFEATED'
  | 'ALLIED';

/** A move the rival has announced but not yet executed. Player has a window to counter. */
export interface RivalTelegraph {
  rivalId: string;
  moveId: string;
  message: string;
  executesAt: number; // ms timestamp
  /** Action type the player dispatches to counter, or null if uncounterable. */
  counteredBy: string | null;
  counterLabel: string | null;
}

/** A negative economic effect currently active from a rival strike. */
export interface RivalPressure {
  rivalId: string;
  kind: 'price' | 'production' | 'brand';
  /** Multiplicative modifier applied to the relevant multiplier (e.g. 0.75 = −25%). */
  multiplier: number;
  endsAt: number; // ms timestamp
}

export interface RivalState {
  id: string;
  aggression: number;    // 0–100
  relationship: number;  // −100 (war) to +100 (allied)
  posture: RivalPosture;
  telegraph: RivalTelegraph | null;
  lastMoveAt: number;    // ms timestamp
  cooldownUntil: number; // ms timestamp
  pendingAggDelta: number;
  // Session 3.3 additions.
  /** Last 5 move IDs the player countered, oldest first. Used for counter-adaptation. */
  defenseHistory: string[];
  /** True when this telegraph is a feint (no effect on execution). */
  telegraphIsFeint: boolean;
  /** How many times the player has directly attacked this rival. */
  timesAttacked: number;
}

// ============================================================================
// Dynasty system (Session 4.5) — prestige chain, earned traits, emergent beats.
// Tracks outcomes of each prestige run; traits persist and compound across
// generations; emergent beats are procedurally generated from dynasty history.
// ============================================================================

export interface DynastyTrait {
  id: string;
  label: string;
  desc: string;
  /** Multiplicative bonus to production (e.g. 1.05 = +5%). */
  prodMult: number;
  /** Fraction cost discount (e.g. 0.03 = 3% off). Additive across traits, capped in engine. */
  costDiscount: number;
}

export interface DynastyRun {
  /** 0-based: 0 = first run (before first prestige). */
  runIdx: number;
  endEarnings: number;
  finalEthics: number;
  /** Companion IDs at LEGACY rung when prestige fired. */
  companionsLegacy: string[];
  /** Rival IDs that reached DEFEATED posture during the run. */
  rivalsBested: string[];
  /** Premise clauses fulfilled at time of prestige. */
  clausesFulfilled: number;
  /** Trait ID earned this run, or null. */
  traitEarned: string | null;
}

export interface DynastyState {
  /** Completed runs, oldest first. */
  runs: DynastyRun[];
  /** Active traits from past runs (at most one new trait per run). */
  traits: DynastyTrait[];
  /** Cosmetic heirloom name strings unlocked at prestige milestones. */
  heirlooms: string[];
}

// ============================================================================
// Echelon system (Session 5.1) — competitive ranking ladder.
// Tier advances as lifetime earnings grow; each tier grants a passive
// production multiplier. Rising in the world attracts press coverage and
// intensifies rival aggression.
// ============================================================================

export type EchelonTier =
  | 'STARTUP'    // < $10K lifetime earnings
  | 'CONTENDER'  // $10K – $1M
  | 'PLAYER'     // $1M – $100M
  | 'LEADER'     // $100M – $10B
  | 'MOGUL'      // $10B – $1T
  | 'TITAN';     // $1T+

export interface EchelonState {
  tier: EchelonTier;
  /** 0–100 progress within current tier. */
  points: number;
  /** ms timestamp when tier last advanced (0 = never). */
  lastAdvancedAt: number;
}

// ============================================================================
// Intel Desk (Session 5.2) — spy network for rival intelligence.
// Commissioning a report investigates whether an active rival telegraph is
// a feint. Reports resolve after 30 s; intel level decays slowly over time.
// ============================================================================

export interface IntelReport {
  rivalId: string;
  commissionedAt: number; // ms
  /** ms — resolves 30 s after commissioned. */
  revealsAt: number;
  resolved: boolean;
  /** null until resolved; true = the current telegraph is a feint. */
  wasFeint: boolean | null;
}

export interface IntelState {
  /** 0–100 network strength. Gained by commissioning reports; decays 2/min. */
  level: number;
  /** Up to 5 most-recent reports. */
  reports: IntelReport[];
  /** ms — gates "Commission" button (300 s cooldown). */
  lastBriefAt: number;
}

// ============================================================================
// Newspaper (Session 5.3) — press coverage system.
// Notable transitions trigger headlines; negative coverage accumulates a heat
// score that applies a small production debuff until the player responds.
// ============================================================================

export type NewsCategory = 'business' | 'scandal' | 'politics' | 'victory' | 'market';

export interface NewsItem {
  id: string;
  at: number;             // ms timestamp
  category: NewsCategory;
  headline: string;
  body: string;
  /** −10 (crisis) to +10 (triumph). */
  sentimentScore: number;
  read: boolean;
  responded: boolean;
}

export interface NewspaperState {
  /** Rolling archive — max 20 items, newest first. */
  items: NewsItem[];
  /** ms — gates new items (min 60 s apart). */
  lastPublishedAt: number;
  /** Accumulated negative coverage (0–100). Decays 0.5/min; respond to reduce. */
  heatScore: number;
}

// ============================================================================
// Notification Engine (Session 5.4) — persistent alert log.
// Priority-ranked history of game events. Urgent alerts also fire toasts.
// ============================================================================

export type NotificationPriority = 'urgent' | 'info' | 'success';

export interface GameNotification {
  id: string;
  at: number; // ms
  priority: NotificationPriority;
  icon: string;
  title: string;
  body: string;
  read: boolean;
}

export interface NotificationState {
  /** Max 50 items, newest first. */
  items: GameNotification[];
  /** ms — items with at > lastSeenAt are "unread". */
  lastSeenAt: number;
}

// ============================================================================
// Director system (Session 3.5) — hardcoded pacing/orchestration layer.
// ============================================================================

/**
 * Broad economic era the player is in. Used to tune rival aggression,
 * companion support, and story pacing without changing the underlying numbers.
 */
export type DirectorPhase =
  | 'BOOTSTRAPPING'   // < $1 000 lifetime
  | 'GROWING'         // $1 000 – $100 000
  | 'SCALING'         // $100 000 – $10 M
  | 'ESTABLISHED'     // $10 M – $1 B
  | 'TITAN';          // $1 B+

export interface DirectorState {
  /** Phase calculated at the last director run. */
  currentPhase: DirectorPhase;
  /** ms timestamp of the last story beat the player acknowledged. */
  lastBeatAt: number;
  /** ms timestamp of last director-triggered escalation. */
  lastEscalationAt: number;
  /** ms timestamp of last companion trust nudge. */
  lastNudgeAt: number;
}

// ============================================================================
// Action discriminated union — one variant per reducer action.
// ============================================================================

export type Action =
  | { type: 'SETUP'; payload: CompanySetup }
  | { type: 'TICK'; dt: number }
  | { type: 'BUY_FACILITY'; id: string; qty: 1 | 10 | 100 | 'max' }
  | { type: 'PRESTIGE' }
  | { type: 'START_RESEARCH'; id: string }
  | { type: 'ADVISOR_RECRUIT'; id: string }
  | { type: 'ADVISOR_LEVEL'; id: string }
  | { type: 'ADVISOR_ASSIGN'; advisorId: string; facilityId: string }
  | { type: 'ADVISOR_ACTIVATE'; id: string }
  | { type: 'STORY_SEEN'; id: string }
  | { type: 'STORY_CHOICE'; beatId: string; optionIndex: number }
  | { type: 'SET_BOOST'; mult: number; seconds: number; source: string }
  | { type: 'EVENT_RESOLVE'; reward?: GameReward; cost?: { cash?: number; influence?: number; lp?: number } }
  | { type: 'SELL_RESOURCE' }
  | { type: 'TOGGLE_STOCKPILE' }
  | { type: 'SET_BUYQTY'; qty: 1 | 10 | 100 | 'max' }
  | { type: 'SET_SETTINGS'; payload: Partial<GameState['settings']> }
  | { type: 'EXPAND_TERRITORY'; id: string }
  | { type: 'MARKETING_UPGRADE'; channelId: string }
  | { type: 'MARKETING_TOGGLE'; channelId: string }
  | { type: 'MARKETING_CAMPAIGN'; id: string }
  | { type: 'CHARACTER_CUSTOMIZE'; payload: Partial<CofounderState> }
  | { type: 'GUIDANCE_SEEN'; id: string }
  | { type: 'GUIDANCE_DISMISS'; id: string }
  | { type: 'TOGGLE_LIVE_VIEW' }
  | { type: 'COMPANION_TRUST'; companionId: string; delta: number }
  | { type: 'COMPANION_ACTIVATE'; companionId: string }
  | { type: 'RIVAL_AGGRESSION'; rivalId: string; delta: number }
  | { type: 'RIVAL_COUNTER'; rivalId: string }
  | { type: 'RIVAL_OFFENSE'; rivalId: string; offenseKind: 'leak_story' | 'fund_competitor' | 'undercut' }
  | { type: 'WORKER_MORALE'; workerId: string; delta: number }
  | { type: 'AIDE_BRIEF'; aideId: string }
  | { type: 'AIDE_DEPLOY'; aideId: string }
  | { type: 'INTEL_COMMISSION'; rivalId?: string }
  | { type: 'NEWS_RESPOND'; itemId: string }
  | { type: 'NOTIFICATION_READ_ALL' }
  | { type: 'LOAD'; state: GameState }
  | { type: 'IMPORT'; state: GameState }
  | { type: 'HARD_RESET' };
